import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { readChartAnchors, workbookCharts, workbookChartParts } from '../../src/Glance.Components/Office/third_party/web/bin/workbook-drawings.mjs';
const require = createRequire(import.meta.url);
const JSZip = require('../../src/Glance.Components/Office/third_party/web/jszip/3.10.1/dist/jszip.min.js');
const drawing = 'http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing';
const chart = 'http://schemas.openxmlformats.org/drawingml/2006/chart';
const relation = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const packageNs = 'http://schemas.openxmlformats.org/package/2006/relationships';
const wrap = body => `<x:wsDr xmlns:x="${drawing}" xmlns:c="${chart}" xmlns:r="${relation}">${body}</x:wsDr>`;
const reference = '<c:chart r:id="chart"/>';
const from = '<x:from><x:col>2</x:col><x:colOff>9525</x:colOff><x:row>3</x:row><x:rowOff>19050</x:rowOff></x:from>';
const one = `<x:oneCellAnchor>${from}<x:ext cx="3810000" cy="2857500"/>${reference}</x:oneCellAnchor>`;
const two = `<x:twoCellAnchor>${from}<x:to><x:col>8</x:col><x:row>20</x:row></x:to>${reference}</x:twoCellAnchor>`;
const absolute = `<x:absoluteAnchor><x:pos x="95250" y="190500"/><x:ext cx="3810000" cy="2857500"/>${reference}</x:absoluteAnchor>`;
const links = new Map([['chart', 'xl/charts/chart1.xml']]);
const anchors = readChartAnchors(wrap(one + two + absolute), links);
assert.equal(anchors.length, 3);
assert.deepEqual(anchors[0].range.tl, { nativeCol: 2, nativeRow: 3, nativeColOff: 9525, nativeRowOff: 19050 });
assert.deepEqual(anchors[0].range.ext, { width: 400, height: 300 });
assert.deepEqual(anchors[1].range.br, { nativeCol: 8, nativeRow: 20, nativeColOff: 0, nativeRowOff: 0 });
assert.deepEqual(anchors[2].range.absolute, { left: 10, top: 20 });
assert.throws(() => readChartAnchors(wrap(one), new Map()), /reference/);
assert.throws(() => readChartAnchors(wrap(one.replace('<x:row>3', '<x:row>-1')), links), /coordinate/);
assert.throws(() => readChartAnchors(wrap(one.replace('3810000', 'NaN')), links), /size/);
assert.throws(() => readChartAnchors(`<!DOCTYPE wsDr>${wrap(one)}`, links), /Document types/);
assert.throws(() => readChartAnchors(wrap(one.repeat(1001)), links), /Too many/);

const zip = new JSZip();
const rels = body => `<Relationships xmlns="${packageNs}">${body}</Relationships>`;
zip.file('xl/worksheets/_rels/sheet7.xml.rels', rels(`<Relationship Id="drawing" Type="${relation}/drawing" Target="../drawings/drawing2.xml"/>`));
zip.file('xl/drawings/drawing2.xml', wrap(one + absolute));
zip.file('xl/drawings/_rels/drawing2.xml.rels', rels(`<Relationship Id="chart" Type="${relation}/chart" Target="../charts/chart1.xml"/>`));
zip.file('xl/charts/chart1.xml', '<chart/>');
zip.file('xl/charts/_rels/chart1.xml.rels', rels('<Relationship Id="style" Type="http://schemas.microsoft.com/office/2011/relationships/chartStyle" Target="style1.xml"/>'));
zip.file('xl/charts/style1.xml', '<style/>');
const archive = { zip, sheets: [{ target: 'xl/worksheets/sheet7.xml' }] };
const result = await workbookCharts(archive, 0, ['drawing']);
assert.equal(result.length, 2);
assert.deepEqual(result.map(item => item.id), [0, 1]);
assert.equal(result[1].path, 'xl/charts/chart1.xml');
const parts = await workbookChartParts(archive, result[0]);
assert.equal(parts.xml, '<chart/>');
assert.deepEqual(parts.styles, [['xl/charts/style1.xml', '<style/>']]);
zip.file('xl/drawings/_rels/drawing2.xml.rels', rels(`<Relationship Id="chart" Type="${relation}/chart" TargetMode="External" Target="https://example.invalid/chart"/>`));
await assert.rejects(workbookCharts(archive, 0, ['drawing']), /relationship/);
console.log('Office workbook drawing regression tests passed');
