#pragma once

#define GLANCE_VERSION_MAJOR 2026
#define GLANCE_VERSION_MINOR 8
#define GLANCE_VERSION_PATCH 19
#define GLANCE_VERSION_REVISION 0

#define GLANCE_VERSION_NUMERIC \
    GLANCE_VERSION_MAJOR, GLANCE_VERSION_MINOR, GLANCE_VERSION_PATCH, GLANCE_VERSION_REVISION
#define GLANCE_VERSION_STRING "2026.08.19"
#define GLANCE_VERSION_WSTRING L"2026.08.19"
#define GLANCE_FILE_VERSION_STRING "2026.8.19.0"
